In [ ]:
import numpy as np # numpy is used to mannupukate data in array                         #Data Analytics
# list are hetrogenous 
# array hare homogenous

In [ ]:
a=np.array([1,2,3,4,5]) # this is how we create array    #1d array
print (a)

[1 2 3 4 5]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
#2d array
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3d array
a3=np.array([[[1,2,3],[3,5,6]],[[7,8,9],[5,8,9]]])
print(a3)


[[[1 2 3]
  [3 5 6]]

 [[7 8 9]
  [5 8 9]]]


In [ ]:
print (a3.shape)#number of rows and coukms

print(a3.ndim)# number of dimensions
print(a3.dtype)# data type of elementsprint

(2, 2, 3)
3
int32


In [ ]:
print (a2.shape)#number of rows and coukms

print(a2.ndim)# number of dimensions
print(a2.dtype)# data type of elementsprint

(2, 3)
2
int32


In [ ]:
np.arange(10)
np.arange(2,21)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
x=np.array([[3,4,5],
            [6,7,8],
            [4,5,6]])

y=x=np.array([[7,8,9],
              [10,11,12],
              [13,14,15]])
print(x)
print(y)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
z=x+y
print(z)

[[14 16 18]
 [20 22 24]
 [26 28 30]]


In [ ]:
print(x*y)

[[ 49  64  81]
 [100 121 144]
 [169 196 225]]


In [ ]:
print(x@y)  #matrix multiplication

[[246 270 294]
 [336 369 402]
 [426 468 510]]


In [ ]:
np.dot(x,y)# matrix mutiplicatiion alternate

array([[246, 270, 294],
       [336, 369, 402],
       [426, 468, 510]])

In [ ]:
x.prod()

1816214400

In [ ]:
x.mean(axis=0) # mean according to coloumn

array([10., 11., 12.])

In [ ]:
x.mean(axis=1) #according to row

array([ 8., 11., 14.])

In [ ]:
print(x.sum()) # sum of all elements
print(x.sum(axis=0)) #sum of each coloumn
print(x.sum(axis=1)) # sum of each row

99
[30 33 36]
[24 33 42]


In [ ]:
print(x.std()) #standard diviation
print(x.var()) #VARIENCE

2.581988897471611
6.666666666666667


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))#median
print(np.percentile(a,25))#1st quartile
print(np.percentile(a,75))#3rd quartile

5.0
3.0
7.0


In [ ]:
b=np.random.randint(11,100,size=(4,4))
print(b)

[[95 28 79 77]
 [87 86 88 53]
 [52 75 97 56]
 [75 41 63 16]]


In [ ]:
print('2x8')
print(b.reshape(2,8))
print('8x2')
print(b.reshape(8,2))

2x8
[[95 28 79 77 87 86 88 53]
 [52 75 97 56 75 41 63 16]]
8x2
[[95 28]
 [79 77]
 [87 86]
 [88 53]
 [52 75]
 [97 56]
 [75 41]
 [63 16]]


In [ ]:
#b=np.random.randint(11,100,size=(3,4,4)) #3d array
#print(b)

[[[13 91 39 33]
  [88 30 79 29]
  [70 66 54 84]
  [40 49 12 76]]

 [[96 35 78 14]
  [81 84 11 62]
  [41 66 33 68]
  [87 85 37 40]]

 [[79 33 50 53]
  [63 43 85 20]
  [98 98 75 32]
  [97 52 70 72]]]


In [ ]:
b=np.random.randint(11,100,size=(4,4))   #generating an array
print(b)

[[47 54 70 87]
 [22 82 40 36]
 [96 12 55 87]
 [20 35 87 32]]


In [ ]:
print([b[0]]) #first row
print(b[0,1])#1st row 2nd column
print (b[-1])
print(b[:3])
print(b[3:])

[array([47, 54, 70, 87])]
54
[20 35 87 32]


TypeError: 'axis' is an invalid keyword argument for print()